export default {
  PHOTO_DATA: {
    IS_PHOTO_DATA_LOADING: 'IS_PHOTO_DATA_LOADING',
    PHOTO_DATA: 'PHOTO_DATA',
    PHOTO_DATA_LOADING_ERROR: 'PHOTO_DATA_LOADING_ERROR',
  },
  PROJECT_DATA: {
    IS_PROJECT_DATA_LOADING: 'IS_PROJECT_DATA_LOADING',
    PROJECT_DATA: 'PROJECT_DATA',
    PROJECT_DATA_LOADING_ERROR: 'PROJECT_DATA_LOADING_ERROR',
  },
  WORK_EXPERIENCE_DATA: {
    IS_WORK_EXPERIENCE_DATA_LOADING: 'IS_WORK_EXPERIENCE_DATA_LOADING',
    WORK_EXPERIENCE_DATA: 'WORK_EXPERIENCE_DATA',
    WORK_EXPERIENCE_DATA_LOADING_ERROR: 'WORK_EXPERIENCE_DATA_LOADING_ERROR',
  },
};
